### ISSUE TITLE
Questions about the original dataset

### ISSUE THREAD

**Issue by carrie0307** [zhufq00/mcnc#1]
Hi, thanks for your release of the code. I am recently working the SEP task and would like to follow your work. Could you please share the original dataset through e-mail? I have sent emails to your gmail.
I am eagerly looking forward to your reply!

Best!

**Comment by zhufq00** [comment]
Sure, I was just uploading the files that need to be loaded with pickle. I think these should be the correct files.

**Comment by carrie0307** [comment]
Hi, I have downloaded the data and thank you very much!

**Comment by carrie0307** [comment]
Fangqi:
  Hi!
  It reports “pickle data was truncated”, when I load the train with pickle (The test and dev data go well). Could you please resend the train dataset again? Thank you very much!

**Comment by zhufq00** [comment]
Since I have emailed you the correct original datasets, I have closed this issue.

**Comment by YuboFeng2023** [comment]
Hi Fangqi,


What a fabulous work you have done!
I think this great work should be focused by most NLP researchers, so could you please release the original data to a public data repository?
Such as Google Drive?

**Comment by zhufq00** [comment]
Hi,


Could you email to ***@***.*** I will email back with the dataset.


Thank you for you ack on our work. Hope you can make some progress in this field.


Best,
Fangqi



---Original---
From: ***@***.***&gt;
Date: Wed, Nov 1, 2023 09:59 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [zhufq00/mcnc] Questions about the original dataset (Issue #1)




 
Hi Fangqi,
 
What a fabulous work you have done!
 I think this great work should be focused by most NLP researchers, so could you please release the original data to a public data repository?
 Such as Google Drive?
