### ISSUE TITLE
模型

### ISSUE THREAD

**Issue by chenzhongwu** [zhufq00/mcnc#2]
请问有已经pretrain+finetune好的模型么，是否可以发给我一份？谢谢

**Comment by zhufq00** [comment]
我之前发过别人finetune的model，性能是62.94，需要我转发给你邮箱吗，pretrain的model我疏忽了，似乎没有保存，抱歉，pretrain大概需要训练40个epoch，参数配置文件里应该有写。

**Comment by zhufq00** [comment]
> 我之前发过别人finetune的model，性能是62.94，需要我转发给你邮箱吗，pretrain的model我疏忽了，似乎没有保存，抱歉，pretrain大概需要训练40个epoch，参数配置文件里应该有写。

I have updated the readme, please check it, thank you for your attention.
